version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper

  rest-service:
    build: ./rest-service
    ports:
      - "8080:8080"
    depends_on:
      - kafka

  calculator-service:
    build: ./calculator-service
    depends_on:
      - kafka